In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/Acmegrade/insurance.csv'
import pandas as pd
df=pd.read_csv(path)
df.head(5)

Mounted at /content/drive


age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [ ]:
df["age"].corr(df["charges"])

0.29900819333064754

In [ ]:
df["bmi"].corr(df["charges"])

0.19834096883362895

In [ ]:
df["children"].corr(df["charges"])

0.0679982268479048

In [ ]:
df2=df[["age","bmi","children","charges"]]
df2.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

In [ ]:
import numpy as np
msk=np.random.rand(len(df2))<0.7
train_df=df2[msk]
test_df=df2[~msk]
train_df.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

In [ ]:
test_df

age     bmi  children      charges
9      60  25.840         0  28923.13692
12     23  34.400         0   1826.84300
19     30  35.300         0  36837.46700
28     23  17.385         1   2775.19215
30     22  35.600         0  35585.57600
...   ...     ...       ...          ...
1330   57  25.740         2  12629.16560
1331   23  33.400         0  10795.93733
1334   18  31.920         0   2205.98080
1336   21  25.800         0   2007.94500
1337   61  29.070         0  29141.36030

[408 rows x 4 columns]

In [ ]:
X_train_df= train_df[["age"]]
print(X_train_df)

      age
0      19
1      18
2      28
3      33
4      32
...   ...
1326   42
1328   23
1332   52
1333   50
1335   18

[930 rows x 1 columns]


In [ ]:
Y_train_df=train_df[["charges"]]
print(Y_train_df)

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1326   7050.02130
1328  22395.74424
1332  11411.68500
1333  10600.54830
1335   1629.83350

[930 rows x 1 columns]


In [ ]:
X_test_df= test_df[["age"]]
Y_test_df=test_df[["charges"]]

In [ ]:
X_train_df=np.asarray(X_train_df)
Y_train_df=np.asarray(Y_train_df)
X_test_df=np.asarray(X_test_df)
Y_test_df=np.asarray(Y_test_df)

In [ ]:
X_train_df

Create a model

In [ ]:
from sklearn import linear_model
clf=linear_model.LinearRegression()
clf.fit(X_train_df,Y_train_df)
c=clf.intercept_
m=clf.coef_

Actual Values

In [ ]:
X_test_df[0:4]

array([[60],
       [23],
       [30],
       [23]])

In [ ]:
Y_test_df[0:4]

array([[28923.13692],
       [ 1826.843  ],
       [36837.467  ],
       [ 2775.19215]])

Test Procedure

In [ ]:
clf.predict(X_test_df[0:4])

array([[18180.17795137],
       [ 9774.71214841],
       [11364.93540843],
       [ 9774.71214841]])

In [ ]:
Y_pred=clf.predict(X_test_df)

In [ ]:
np.mean(np.abs(Y_pred-Y_test_df))

8965.450003122984